server.port: 8085

server.context-path: /huang
cupSize: A
age: 18
content: "cupSize:${cupSize},age:${age}"

girl.CupSize: B
girl.Age: 16

spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://127.0.0.1:3306/hibernate
spring.datasource.username: root
spring.datasource.password: 0408

spring.jpa.hibernate.ddl-auto: update
spring.jpa.hibernate.show-sql: true


